name: Build and Release SetInput

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET (LTS Only)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          include-prerelease: false

      - name: Check installed .NET version
        run: |
          $version = dotnet --version
          if ($version -notmatch "^8\.0\.\d+$") {
            Write-Error "Invalid .NET SDK version detected: $version. Expected 8.0.x."
            exit 1
          }
        shell: pwsh

      - name: Build SingleFile Version
        run: |
          dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true -o ./publish/Single
          Rename-Item ./publish/Single/SetInput.exe SetInput_Single.exe

      - name: Build SelfContained Version
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ./publish/SelfContained
          Rename-Item ./publish/SelfContained/SetInput.exe SetInput_SelfContained.exe

      - name: Upload EXEs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SetInput_Single.exe
            SetInput_SelfContained.exe
