name: Build and Release SetInput

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check GitHub Runner Version
        run: |
          Write-Host "Running on GitHub Runner OS: $env:RUNNER_OS"
          Write-Host "Runner Image: $env:ImageOS"

          if ($env:ImageOS -notmatch "(?i)(windows|win)") {
            Write-Error "Unsupported runner detected! This workflow requires a Windows runner."
            exit 1
          } else {
            Write-Host "✅ Windows-compatible Runner detected: $env:ImageOS"
          }
        shell: pwsh

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 8 LTS
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Confirm Correct .NET Version
        run: |
          $version = dotnet --version
          if ($version -notmatch "^8\.0\.\d+$") {
            Write-Host "Installed .NET version: $version"
            throw "Invalid .NET SDK version detected. Expected 8.0.x."
          } else {
            Write-Host "✅ Correct .NET version detected: $version"
          }
        shell: pwsh

      - name: Build SingleFile Version
        run: |
          dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true -o ./publish/Single
          Rename-Item ./publish/Single/SetInput.exe SetInput_Single.exe
        shell: pwsh

      - name: Build SelfContained Version
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ./publish/SelfContained
          Rename-Item ./publish/SelfContained/SetInput.exe SetInput_SelfContained.exe
        shell: pwsh

      - name: Upload EXEs to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SetInput_Single.exe
            SetInput_SelfContained.exe
