name: Build and Release SetInput

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Release SingleFile
        run: |
          dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true -o ./publish/Single
          Rename-Item ./publish/Single/SetInput.exe SetInput_Single.exe

      - name: Build Release SelfContained
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true -o ./publish/SelfContained
          Rename-Item ./publish/SelfContained/SetInput.exe SetInput_SelfContained.exe

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SetInput_Builds
          path: |
            publish/Single/SetInput_Single.exe
            publish/SelfContained/SetInput_SelfContained.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: SetInput_Builds
          path: release-files

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release-files/SetInput_Single.exe
            release-files/SetInput_SelfContained.exe
